### ISSUE TITLE
btw, got a 404 from a link in the GitHub wiki

### ISSUE THREAD

**Issue by hangtwenty** [h1st-ai/h1st#107]
Really minor thing, just letting you know.

On the GitHub wiki, there's a link in the sidebar: https://h1st.ai/Introduction.html - it's labeled as "Why H1st?". That link leads to a 404 now.

**EDIT:** The fixed link is: https://www.h1st.ai/tutorials/why-h1st-ai

**Comment by hangtwenty** [comment]
To fix it:

`git clone https://github.com/h1st-ai/h1st.wiki.git`

```patch
diff --git a/_Sidebar.md b/_Sidebar.md
index 2bcd1aa..b07a349 100644
--- a/_Sidebar.md
+++ b/_Sidebar.md
@@ -1,5 +1,5 @@
 * [What is a Model?](https://github.com/h1st-ai/h1st/wiki/Human-First-AI-Model-Explained)
 * [What is a Graph?](https://github.com/h1st-ai/h1st/wiki/Human-First-AI-Graph-Explained)
-* [Why H1st?](https://h1st.ai/Introduction.html)
+* [Why H1st?](https://www.h1st.ai/tutorials/why-h1st-ai)
```

(I just did this myself but then remembered I can't push to your wiki. Or I forgot how to do so. I can't remember what I forgot 😉 )

**Comment by ctn** [comment]
Merged https://github.com/h1st-ai/h1st/pull/108, thanks.
