### ISSUE TITLE
Clean up blank `__init__.py` files, which are not required by Python 3.x

### ISSUE THREAD

**Issue by TheVinhLuong102** [h1st-ai/h1st#111]
Various `h1st` submodules still contain `__init__.py` files that are empty, containing neither useful initialization code nor "public" API classes / functions for those submodules.

Such empty `__init__.py` files are unnecessary in Python 3.x and should be cleaned up.

**Comment by ctn** [comment]
OK if we remove all empty __init__.py @nhanitvn @Shiti @phanhongan et al.?
