### ISSUE TITLE
H1st not installable on Py3.10

### ISSUE THREAD

**Issue by TheVinhLuong102** [h1st-ai/h1st#150]
Currently installing H1st with Python 3.10 encounters a Poetry-related error, even when the Python requirement range is extended to cover Python 3.10.

The error message says either `ModuleNotFoundError: No module named 'distutils.util'` or `ModuleNotFoundError: No module named 'poetry'`

**Comment by TheVinhLuong102** [comment]
@khoama could you help unblock this?

**Comment by vuonghoainam** [comment]
This should be fixed by #152 and #153
