### ISSUE TITLE
Create a simple HelloWorld Graph to demonstrate its use and power

### ISSUE THREAD

**Issue by ctn** [h1st-ai/h1st#20]
Create a simple runnable "hello world" graph.

Demonstrate how to use 1. simple node & 2. decision node.

Explain data flow & control flow / execution.

**Comment by ctn** [comment]
@TheVinhLuong102 this is a good exercise for you from a high-level perspective. Also please create a corresponding Wiki page to explain (a) motivation, (b) basic design principles, and (c) current support for *H1st Graphs*

**Comment by aht** [comment]
https://github.com/h1st-ai/h1st/wiki/Human-First-AI-Graph-Explained

I'll add a quick start section to README & API doc site w other pages.

**Comment by aht** [comment]
https://github.com/h1st-ai/h1st/pull/51/
