### ISSUE TITLE
AutomotiveCybersecurity is just too long...

### ISSUE THREAD

**Issue by ctn** [h1st-ai/h1st#24]
Can we rename the package to `AutoCyber`?

Cc @nhanitvn @TgithubJ

**Comment by TgithubJ** [comment]
@ctn Let me handle it after aht's tutorial update.

**Comment by TgithubJ** [comment]
Please review #45  @ctn

**Comment by aht** [comment]
Right now the folder is flattened so "AutomotiveCybersecurity" is entirely gone from the imports (it's just `import util` e.g. not `from AutomotiveCybersecurity import util`.

So it just remains as the name of the example folder. I think that it's fine to leave.
