### ISSUE TITLE
Contributors: we can use more "HelloWorld" examples for new users to get started easily.

### ISSUE THREAD

**Issue by ctn** [h1st-ai/h1st#5]
Add ideas/suggestions here and we'll discuss/greenlight them. Thanks.

**Comment by nqbao** [comment]
We have a HelloWorld example for MLModel & RuleBasedModel here https://github.com/h1st-ai/h1st/tree/master/examples/HelloWorld

I think we can close this issue.

**Comment by aht** [comment]
This needs to be written up as a simple quick start guide in the API doc or wiki & README.

**Comment by aht** [comment]
https://github.com/h1st-ai/h1st/pull/51
