### ISSUE TITLE
"pip3 install h1st" using python 3.9 doesnot work on win 10

### ISSUE THREAD

**Issue by vietnv** [h1st-ai/h1st#56]
**Describe the bug**
On window 10, python version is 3.9. When running "pip3 install h1st", the following error showed:
 ERROR: Command errored out with exit status 1:
     command: 'c:\python39\python.exe' -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\VietNV\\AppData\\Local\\Temp\\pip-install-sak903ey\\h1st\\setup.py'"'"'; __file__='"'"'C:\\Users\\VietNV\\AppData\\Local\\Temp\\pip-install-sak903ey\\h1st\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base 'C:\Users\VietNV\AppData\Local\Temp\pip-pip-egg-info-y9mm4mm8'
         cwd: C:\Users\VietNV\AppData\Local\Temp\pip-install-sak903ey\h1st\
    Complete output (7 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\VietNV\AppData\Local\Temp\pip-install-sak903ey\h1st\setup.py", line 18, in <module>
        long_description = f.read()
      File "c:\python39\lib\encodings\cp1252.py", line 23, in decode
        return codecs.charmap_decode(input,self.errors,decoding_table)[0]
    UnicodeDecodeError: 'charmap' codec can't decode byte 0x9d in position 507: character maps to <undefined>
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.

**To Reproduce**
1. Go to Command Prompt
2. Run "pip3 install h1st"
3. See error

**Expected behavior**
It should install h1st successfully without any error.

**Desktop (please complete the following information):**
 - OS:  win 10 home

**Comment by nqbao** [comment]
Hi @vietnv, thank you for reporting. I see you report both #56 and #57. Is this one for win 10 64bit?

**Comment by vietnv** [comment]
Hi @nqbao,
Yes, this is for win 10 64bit.
Anyway, after work a round some hours, I re-install python 3.7.8  64bit on this win 10, finally I can install h1st successfully.

**Comment by Devansh2005** [comment]
I'm also getting the same error. Reinstalling the python also didn't work in my case.

**Comment by nqbao** [comment]
Hi @Devansh2005 , I'm looking for a windows laptop to test now. In the meanwhile, can you help me try to install directly in github? And if it does not work can you try [anaconda/miniconda](https://www.anaconda.com/)?

Thanks!

**Comment by Devansh2005** [comment]
I have tried to install it in anaconda and it is giving me the same error sir @nqbao .

**Comment by nqbao** [comment]
Hi @Devansh2005 , yeah i'm trying to reproduce in windows to fix the issue. Thank for being patient!

**Comment by ctn** [comment]
Any updates?

**Comment by nqbao** [comment]
I have sent the PR here https://github.com/h1st-ai/h1st/pull/58, will do some more testing before resolving the issue.

**Comment by nqbao** [comment]
@Devansh2005 can you check the latest version on master? I have tested on Parallels & windows with Python 3.8. Please let me know if you still have problems

**Comment by Devansh2005** [comment]
Hey @nqbao, I'm still facing the same error as described in #56.

**Comment by nqbao** [comment]
@Devansh2005 did you use `pip install h1st` ?

**Comment by Devansh2005** [comment]
I have used this command in cmd win 10 with python 3.7 installed in 64 bit windows

**Comment by nqbao** [comment]
@Devansh2005 can you try 

```
pip install -U git+https://github.com/h1st-ai/h1st
```

I haven't updated on pypi yet

**Comment by Devansh2005** [comment]
This works well @nqbao . Thank You !

**Comment by Devansh2005** [comment]
c:\users\devansh\appdata\local\pip\cache\wheels\ca\cb\e5\ac701e12d365a08917bf4c6171c0961bc880a8181359c66aa7
  Building wheel for shap (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: 'c:\pyhton\python37\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\Devansh\\AppData\\Local\\Temp\\pip-install-frim2fd4\\shap\\setup.py'"'"'; __file__='"'"'C:\\Users\\Devansh\\AppData\\Local\\Temp\\pip-install-frim2fd4\\shap\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d 'C:\Users\Devansh\AppData\Local\Temp\pip-wheel-vska47nx'
       cwd: C:\Users\Devansh\AppData\Local\Temp\pip-install-frim2fd4\shap\
  Complete output (67 lines):
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build\lib.win-amd64-3.7
  creating build\lib.win-amd64-3.7\shap
  copying shap\common.py -> build\lib.win-amd64-3.7\shap
  copying shap\datasets.py -> build\lib.win-amd64-3.7\shap
  copying shap\__init__.py -> build\lib.win-amd64-3.7\shap
  creating build\lib.win-amd64-3.7\shap\explainers
  copying shap\explainers\additive.py -> build\lib.win-amd64-3.7\shap\explainers
  copying shap\explainers\bruteforce.py -> build\lib.win-amd64-3.7\shap\explainers
  copying shap\explainers\explainer.py -> build\lib.win-amd64-3.7\shap\explainers
  copying shap\explainers\gradient.py -> build\lib.win-amd64-3.7\shap\explainers
  copying shap\explainers\kernel.py -> build\lib.win-amd64-3.7\shap\explainers
  copying shap\explainers\linear.py -> build\lib.win-amd64-3.7\shap\explainers
  copying shap\explainers\mimic.py -> build\lib.win-amd64-3.7\shap\explainers
  copying shap\explainers\partition.py -> build\lib.win-amd64-3.7\shap\explainers
  copying shap\explainers\permutation.py -> build\lib.win-amd64-3.7\shap\explainers
  copying shap\explainers\pytree.py -> build\lib.win-amd64-3.7\shap\explainers
  copying shap\explainers\sampling.py -> build\lib.win-amd64-3.7\shap\explainers
  copying shap\explainers\tf_utils.py -> build\lib.win-amd64-3.7\shap\explainers
  copying shap\explainers\tree.py -> build\lib.win-amd64-3.7\shap\explainers
  copying shap\explainers\__init__.py -> build\lib.win-amd64-3.7\shap\explainers
  creating build\lib.win-amd64-3.7\shap\explainers\other
  copying shap\explainers\other\coefficent.py -> build\lib.win-amd64-3.7\shap\explainers\other
  copying shap\explainers\other\lime.py -> build\lib.win-amd64-3.7\shap\explainers\other
  copying shap\explainers\other\maple.py -> build\lib.win-amd64-3.7\shap\explainers\other
  copying shap\explainers\other\random.py -> build\lib.win-amd64-3.7\shap\explainers\other
  copying shap\explainers\other\treegain.py -> build\lib.win-amd64-3.7\shap\explainers\other
  copying shap\explainers\other\__init__.py -> build\lib.win-amd64-3.7\shap\explainers\other
  creating build\lib.win-amd64-3.7\shap\explainers\deep
  copying shap\explainers\deep\deep_pytorch.py -> build\lib.win-amd64-3.7\shap\explainers\deep
  copying shap\explainers\deep\deep_tf.py -> build\lib.win-amd64-3.7\shap\explainers\deep
  copying shap\explainers\deep\__init__.py -> build\lib.win-amd64-3.7\shap\explainers\deep
  creating build\lib.win-amd64-3.7\shap\plots
  copying shap\plots\bar.py -> build\lib.win-amd64-3.7\shap\plots
  copying shap\plots\colorconv.py -> build\lib.win-amd64-3.7\shap\plots
  copying shap\plots\colors.py -> build\lib.win-amd64-3.7\shap\plots
  copying shap\plots\decision.py -> build\lib.win-amd64-3.7\shap\plots
  copying shap\plots\dependence.py -> build\lib.win-amd64-3.7\shap\plots
  copying shap\plots\embedding.py -> build\lib.win-amd64-3.7\shap\plots
  copying shap\plots\force.py -> build\lib.win-amd64-3.7\shap\plots
  copying shap\plots\force_matplotlib.py -> build\lib.win-amd64-3.7\shap\plots
  copying shap\plots\image.py -> build\lib.win-amd64-3.7\shap\plots
  copying shap\plots\monitoring.py -> build\lib.win-amd64-3.7\shap\plots
  copying shap\plots\partial_dependence.py -> build\lib.win-amd64-3.7\shap\plots
  copying shap\plots\summary.py -> build\lib.win-amd64-3.7\shap\plots
  copying shap\plots\text.py -> build\lib.win-amd64-3.7\shap\plots
  copying shap\plots\waterfall.py -> build\lib.win-amd64-3.7\shap\plots
  copying shap\plots\__init__.py -> build\lib.win-amd64-3.7\shap\plots
  creating build\lib.win-amd64-3.7\shap\benchmark
  copying shap\benchmark\experiments.py -> build\lib.win-amd64-3.7\shap\benchmark
  copying shap\benchmark\measures.py -> build\lib.win-amd64-3.7\shap\benchmark
  copying shap\benchmark\methods.py -> build\lib.win-amd64-3.7\shap\benchmark
  copying shap\benchmark\metrics.py -> build\lib.win-amd64-3.7\shap\benchmark
  copying shap\benchmark\models.py -> build\lib.win-amd64-3.7\shap\benchmark
  copying shap\benchmark\plots.py -> build\lib.win-amd64-3.7\shap\benchmark
  copying shap\benchmark\__init__.py -> build\lib.win-amd64-3.7\shap\benchmark
  creating build\lib.win-amd64-3.7\shap\plots\resources
  copying shap\plots\resources\bundle.js -> build\lib.win-amd64-3.7\shap\plots\resources
  copying shap\plots\resources\logoSmallGray.png -> build\lib.win-amd64-3.7\shap\plots\resources
  copying shap\tree_shap.h -> build\lib.win-amd64-3.7\shap
  running build_ext
  numpy.get_include() c:\pyhton\python37\lib\site-packages\numpy\core\include
  building 'shap._cext' extension
  error: Microsoft Visual C++ 14.0 is required. Get it with "Build Tools for Visual Studio": https://visualstudio.microsoft.com/downloads/
  ----------------------------------------
  ERROR: Failed building wheel for shap
  Running setup.py clean for shap
  Building wheel for pyrsistent (setup.py) ... done
  Created wheel for pyrsistent: filename=pyrsistent-0.17.3-cp37-cp37m-win_amd64.whl size=55878 sha256=4ed7d594a1db5c2e65f177602429d97cb28e0ed3783c8fb91999e245c19e6bb6
  Stored in directory: c:\users\devansh\appdata\local\pip\cache\wheels\a5\52\bf\71258a1d7b3c8cbe1ee53f9314c6f65f20385481eaee573cc5
Successfully built h1st Colored lime pyrsistent
Failed to build shap


At last I faced this error.

**Comment by nqbao** [comment]
@Devansh2005  You will need to install VS Build Tools as well, please follow the link to download and install it. I have also updated the note for installation on Windows.
