### ISSUE TITLE
"pip3 install h1st" run with error on python3.7 32 bit

### ISSUE THREAD

**Issue by vietnv** [h1st-ai/h1st#57]
**Describe the bug**
If using python 3.7 32 bit on window 10, when running "pip3 install h1st", the following error ocurs:
PS C:\users\VietNV\AppData\Local\Programs\Python\Python37-32\Scripts> ./pip3 install h1st
Requirement already satisfied: h1st in c:\users\vietnv\appdata\local\programs\python\python37-32\lib\site-packages\h1st-2020.8-py3.7.egg (2020.8)
Collecting NumPy<1.19,>=1.18.4
  Using cached numpy-1.18.5-cp37-cp37m-win32.whl (10.8 MB)
Collecting Pandas<1.2,>=1.0.4
  Using cached pandas-1.1.3-cp37-cp37m-win32.whl (7.8 MB)
Collecting PyArrow>=0.17.1
  Using cached pyarrow-1.0.1.tar.gz (1.3 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
    Preparing wheel metadata ... done
Requirement already satisfied: cloudpickle==1.3.0 in c:\users\vietnv\appdata\local\programs\python\python37-32\lib\site-packages (from h1st) (1.3.0)
ERROR: Could not find a version that satisfies the requirement Ray==0.8.6 (from h1st) (from versions: none)
ERROR: No matching distribution found for Ray==0.8.6 (from h1st)
PS C:\users\VietNV\AppData\Local\Programs\Python\Python37-32\Scripts>

**To Reproduce**
1. Go to Window PowerShell
2. Run "pip3 install h1st"
3. See error

**Expected behavior**
If h1st module doesnot work with python 32-bit, please mention this in userguide.

**Desktop (please complete the following information):**
 - OS: Win 10 Home

**Comment by ctn** [comment]
Should close this in favor of #56

**Comment by nqbao** [comment]
I updated README to mention that it does not work on 32bit. Thanks for reporting
