### ISSUE TITLE
Put roadmap etc. in wiki

### ISSUE THREAD

**Issue by ctn** [h1st-ai/h1st#6]
https://github.com/h1st-ai/h1st/wiki 

so users can see what's coming down the pike, and contributors can also help fill in the blanks.

@TheVinhLuong102

**Comment by TheVinhLuong102** [comment]
The roadmap can be found in this wiki: https://github.com/h1st-ai/h1st/wiki/Human-First-AI-Roadmap, which will be updated continuously to reflect the latest plan.
